name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
    
    - name: Setup golangci-lint
      run: go install github.com/go-task/task/v3/cmd/task@latest

    - name: Setup tooling
      run: task tooling
    
    - name: Format
      run: task fmt

    - name: Lint
      run: task lint

    - name: Test
      run: task test

    - name: Build
      run: task build
