name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Setup tooling
      run: make tooling

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Check Coverage
      run: make check-coverage 

    - name: Build
      run: make build
